services:
  - type: web
    name: passgen
    env: node
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 